### ISSUE TITLE
encode() does'nt accept integers

### ISSUE THREAD

**Issue by mlang38** [brianfreytag/php-bijective#1]
In the docBlock of the encode() method you say that the $int parameter must be an integer. But if you supply an integer, the ctype_digit() function returns false because ctype_digit() only take strings as parameter. If you supply an integer to ctype_digit(), it interprets it as a ASCII char code. You should test if the $int parameter is_string() before ctype_digit().

**Comment by mlang38** [comment]
Unit tests are your friends to see this :wink:

**Comment by brianfreytag** [comment]
I'll work on this.

This libary was used for a very specific purpose on a project I was working on. I honestly didn't expect people besides me to actually use it. Originally, I was doing an is_int(), then changed it to ctype_digit() when I realized the way my project was going to pass it into it was as a string. Due to the limited projected scope of this library and time constraints, I forewent updating the docBlocks or writing any unit tests.

**Comment by brianfreytag** [comment]
@mlang38 

This is resolved in v1.0.1 and dev-master. Please update accordingly.

I also added some unit tests for you :)

**Comment by mlang38** [comment]
Ok, great job Brian !
Sorry for not responding yesterday, I was at an Agile conference. I use your translator to convert a counter in alphabetic format ( 0 => A, 1 => B ...), in order to generate IDs. I began to implement it using base_convert but I found your lib and thanks to composer it's so easy to integrate it in a Symfony project.

Thx !!
